"""empty message

Revision ID: 2c05c460129d
Revises: f2e9c369e391
Create Date: 2020-04-17 11:08:26.158518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c05c460129d'
down_revision = 'f2e9c369e391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_eventname', table_name='event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_event_eventname', 'event', ['eventname'], unique=1)
    # ### end Alembic commands ###
