"""other table

Revision ID: 89ddfed69469
Revises: 2ac7411b1284
Create Date: 2020-04-14 23:52:02.718554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ddfed69469'
down_revision = '2ac7411b1284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventname', sa.String(length=64), nullable=True),
    sa.Column('eventdate', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('eventtimestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_eventdate'), 'event', ['eventdate'], unique=False)
    op.create_index(op.f('ix_event_eventname'), 'event', ['eventname'], unique=True)
    op.create_index(op.f('ix_event_eventtimestamp'), 'event', ['eventtimestamp'], unique=False)
    op.create_table('attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendeename', sa.String(length=64), nullable=True),
    sa.Column('attendeeemail', sa.String(length=120), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('attendeetimestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendee_attendeeemail'), 'attendee', ['attendeeemail'], unique=True)
    op.create_index(op.f('ix_attendee_attendeename'), 'attendee', ['attendeename'], unique=True)
    op.create_index(op.f('ix_attendee_attendeetimestamp'), 'attendee', ['attendeetimestamp'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messagesubject', sa.String(length=40), nullable=True),
    sa.Column('messagebody', sa.String(length=200), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('messagetimestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_messagetimestamp'), 'message', ['messagetimestamp'], unique=False)
    op.add_column('user', sa.Column('useremail', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_useremail'), 'user', ['useremail'], unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_event_id', table_name='user')
    op.drop_column('user', 'email')
    op.drop_column('user', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('event_id', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_user_event_id', 'user', ['event_id'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_index(op.f('ix_user_useremail'), table_name='user')
    op.drop_column('user', 'useremail')
    op.drop_index(op.f('ix_message_messagetimestamp'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_attendee_attendeetimestamp'), table_name='attendee')
    op.drop_index(op.f('ix_attendee_attendeename'), table_name='attendee')
    op.drop_index(op.f('ix_attendee_attendeeemail'), table_name='attendee')
    op.drop_table('attendee')
    op.drop_index(op.f('ix_event_eventtimestamp'), table_name='event')
    op.drop_index(op.f('ix_event_eventname'), table_name='event')
    op.drop_index(op.f('ix_event_eventdate'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
