"""fix attendee

Revision ID: 9dfa860eecf5
Revises: 2c05c460129d
Create Date: 2020-04-28 22:01:30.663424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfa860eecf5'
down_revision = '2c05c460129d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendee_attendeeemail', table_name='attendee')
    op.create_index(op.f('ix_attendee_attendeeemail'), 'attendee', ['attendeeemail'], unique=False)
    op.drop_index('ix_attendee_attendeename', table_name='attendee')
    op.create_index(op.f('ix_attendee_attendeename'), 'attendee', ['attendeename'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendee_attendeename'), table_name='attendee')
    op.create_index('ix_attendee_attendeename', 'attendee', ['attendeename'], unique=1)
    op.drop_index(op.f('ix_attendee_attendeeemail'), table_name='attendee')
    op.create_index('ix_attendee_attendeeemail', 'attendee', ['attendeeemail'], unique=1)
    # ### end Alembic commands ###
