"""empty message

Revision ID: a0fb43ace1d0
Revises: 85dddd4813b5
Create Date: 2020-05-04 12:32:17.738511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0fb43ace1d0'
down_revision = '85dddd4813b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('useremail', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('event_id', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_useremail'), 'user', ['useremail'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventname', sa.String(length=64), nullable=True),
    sa.Column('eventdate', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('eventtimestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_eventdate'), 'event', ['eventdate'], unique=False)
    op.create_index(op.f('ix_event_eventtimestamp'), 'event', ['eventtimestamp'], unique=False)
    op.create_table('attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendeename', sa.String(length=64), nullable=True),
    sa.Column('attendeeemail', sa.String(length=120), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('attendeetimestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendee_attendeeemail'), 'attendee', ['attendeeemail'], unique=False)
    op.create_index(op.f('ix_attendee_attendeename'), 'attendee', ['attendeename'], unique=False)
    op.create_index(op.f('ix_attendee_attendeetimestamp'), 'attendee', ['attendeetimestamp'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messagesubject', sa.String(length=40), nullable=True),
    sa.Column('messagebody', sa.String(length=200), nullable=True),
    sa.Column('messagestatus', sa.String(length=40), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('messagetimestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_messagetimestamp'), 'message', ['messagetimestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_messagetimestamp'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_attendee_attendeetimestamp'), table_name='attendee')
    op.drop_index(op.f('ix_attendee_attendeename'), table_name='attendee')
    op.drop_index(op.f('ix_attendee_attendeeemail'), table_name='attendee')
    op.drop_table('attendee')
    op.drop_index(op.f('ix_event_eventtimestamp'), table_name='event')
    op.drop_index(op.f('ix_event_eventdate'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_useremail'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
