"""empty message

Revision ID: ac6f6d3ef41e
Revises: 1f5acef6320d
Create Date: 2020-04-15 18:29:29.582048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6f6d3ef41e'
down_revision = '1f5acef6320d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'event_id')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('event_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
