"""empty message

Revision ID: dcc98a7ef161
Revises: ac6f6d3ef41e
Create Date: 2020-04-15 18:34:04.434278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc98a7ef161'
down_revision = 'ac6f6d3ef41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'event_id')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('event_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
