"""empty message

Revision ID: f2e9c369e391
Revises: dcc98a7ef161
Create Date: 2020-04-15 18:44:09.108740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e9c369e391'
down_revision = 'dcc98a7ef161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
